* Name: Marisa Shuman

** Flask Assignment

** Week 2 Link:
https://replit.com/join/ycvoklfycb-mshuman8

** Routes 
/
/index
/game
/randomFacts

* Use of Sessions: 
The first page takes in a UserName -- if the user types "Angle" (my cat's name) then it says not to use the site and to try again. Otherwise it allows the user access to the game picker and random facts.
I also included a visit count on every page.

* Use of Forms:
The first form is on the login page where the user needs to type their username -- it will then check the username
The second form is on the /game (the index.html). It allows the user to select from various game qualities to identify the best game to play.


** Week 1 Link: 
https://replit.com/join/ycvoklfycb-mshuman8
(same as week 2 -- I added to it)

** Routes
/index 
/randomFacts






* Instructions

** If you are presenting this unit:

*** Upload instructions
Upload all content relating to the delivery of your unit. Include the
prework, slides, content etc.

Please use these filenames:
- *homework.md*, *homework.pdf*, or *homework.docx* for the homework
  assignment
- *prework.md*, *prework.pdf*, or *prework.docx* if you are giving
  links to videos or online resources for prework
- Other files should be given names that make sense
*** Assigning the work
- make sure to post the prework one week before your presentation in
  the #cstopics-async channel.
- make sure to post the homework after your group presentation in the
  #cstopics-hw channel.
  
** If you are completing the homework for this unit:

The homework will be posted in the #cstopics-hw channel.

Upload your solutions to the assigned homework in the appropriate
folder. Make sure to use the filenames specified in the assignments.

